# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: snjx.nksm
# email: shinji-nakashima@wacom-it.co.jp
description: > # this means to ignore newlines until "baseurl:"
  いろいろメモしていきますよ。
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
# twitter_username: ""
github_username:  snjxnksm

# Build settings
markdown: kramdown
kramdown:
  input: GFM

theme: jekyll-theme-architect
permalink: /blog/:year/:month/:day/:title.html
local: ja-jp

paginate: 10

# Include custom directories
include: ['_pages']

gems:
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-paginate
